Doctor/urls.py
from django.urls import path, re_path, include

from . import views
urlpatterns = [
    path('', views.index, name='D_index'),
    path('signup/', views.signup, name='D_signup'),
    path('login/', views.loginform, name='D_login'),
    re_path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='D_activate'),
    path('profile/', views.profile_page, name='D_profile'),
    path('schedule/', views.doctorScheduleView, name='doctorSchedule'),
    path('editschedule/', views.editDoctorSchedule, name='editDoctorSchedule'),
    path('ajax/load-areas/', views.load_areas, name='D_ajax_load_areas'),
    path('edit-profile/', views.edit_profile, name='D_edit_profile'),
    path('logout/', views.user_logout, name='logout'),
    re_path('feedback/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.takeFeedback, name='D_feedback'),
    path('createblog/', views.createBlog, name='create-blog'),
]

Main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='Main_index'),
    path('login/', views.index1, name='Login_index'),
    path('signup/', views.index2, name='Signup_index'),

]

Morbus_Praedictum/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from miscellaneous import views as miscViews
from Doctor import views as doc_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('patient/', include('Patient.urls')),
    path('doctor/', include('Doctor.urls')),
    path('company/', include('Corporate.urls')),
    path('feedback/', miscViews.feedbackView, name="Feedback_html"),
    path('api/', include('apis.urls')),
    path('misc/', include('miscellaneous.urls')),
    path('blogs/', doc_views.allThemBlogs, name='blogs'),
    path('blogs/@<str:username>/', doc_views.allBlogs, name='all-blogs'),
    path('blogs/@<str:username>/<str:blog_title>', doc_views.blogDetail, name='blog-detail')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Doctor/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from datetime import time
from django.forms import formset_factory
import sys
from Patient.models import City, Area, Profile
from Corporate.models import Company

HOUR_CHOICES = [(time(hour=x), '{:02d}:00'.format(x)) for x in range(0, 24)]

GENDER_CHOICES = (
    (1, 'Male'),
    (2, 'Female'),
    (3, 'Transgender'),
    (4, 'Other')
)

SPECIALIZATION_CHOICES = (('Nephrologist', 'Nephrologist'), ('Psychiatrist', 'Psychiatrist'), ('Anesthesiologist', 'Anesthesiologist'), ('Podiatrist', 'Podiatrist'), ('Gynecologist', 'Gynecologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Allergist', 'Allergist'), ('Sports Medicine Specialist', 'Sports Medicine Specialist'), ('Medical Geneticist', 'Medical Geneticist'), ('Pulmonologist', 'Pulmonologist'), ('Orthopedist', 'Orthopedist'), ('Diabetologist', 'Diabetologist'), ('Oncologist', 'Oncologist'), ('Sleep Specialist', 'Sleep Specialist'), ('Colon Surgeon', 'Colon Surgeon'), ('Emergency Medicine Specialist', 'Emergency Medicine Specialist'), ('Physiatrist', 'Physiatrist'), ('Neurologist', 'Neurologist'), ('General Physician', 'General Physician'), ('Ophthalmologist', 'Ophthalmologist'), ('Neurosurgeon', 'Neurosurgeon'), ('Urologist', 'Urologist'), ('Pediatrician', 'Pediatrician'), ('Preventive Medicine Specialist', 'Preventive Medicine Specialist'), ('Cardiologist', 'Cardiologist'), ('Sleep Medicine Specialist', 'Sleep Medicine Specialist'), ('Critical Care Medicine Specialist', 'Critical Care Medicine Specialist'), ('General Surgeon', 'General Surgeon'), ('Pathologist', 'Pathologist'), ('Rheumatologist', 'Rheumatologist'), ('Palliative Medicine Specialist', 'Palliative Medicine Specialist'), ('Geriatric Medicine Specialist', 'Geriatric Medicine Specialist'), ('Osteopath', 'Osteopath'), ('Colon and Rectal Surgeon', 'Colon and Rectal Surgeon'), ('Family Physician', 'Family Physician'), ('Endocrinologist', 'Endocrinologist'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Radiologist', 'Radiologist'), ('Otolaryngologist', 'Otolaryngologist'), ('Hematologist', 'Hematologist'), ('Dermatologist', 'Dermatologist'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Obstetricians', 'Obstetricians'))

QUALIFICATION_CHOICES = (
    ('MBBS','MBBS'),
    ('MS','MS'),
    ('MD','MD'),
    ('DCH','DCH'),
    ('BSc','BSc'),
)

DAYS = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
    ('Sunday', 'Sunday')
)

INTERVALS = (
    (0, None),
    (1, '15 Minutes'),
    (2, '30 Minutes'),
    (3, '45 Minutes'),
)

slotTimeChoices = (
    (None, 'None'),
    (10, '10 min'),
    (15, '15 min'),
    (20, '20 min'),
    (30, '30 min'),
    (60, '60 min')
)

TimeChoices = (
    (None, "Closed"),
    ('00:00:00', '00:00'),
    ('00:30:00', '00:30'),
    ('01:00:00', '01:00'),
    ('01:30:00', '01:30'),
    ('02:00:00', '02:00'),
    ('03:00:00', '03:00'),
    ('04:00:00', '04:00'),
    ('05:00:00', '05:00'),
    ('06:00:00', '06:00'),
    ('07:00:00', '07:00'),
    ('08:00:00', '08:00'),
    ('09:00:00', '09:00'),
    ('10:00:00', '10:00'),
    ('11:00:00', '11:00'),
    ('12:00:00', '12:00'),
)


class ClinicAddress(models.Model):
    ClinicAddress_ID = models.AutoField(primary_key=True, auto_created=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    Home = models.CharField(max_length=250)
    Street = models.CharField(max_length=250)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    area = models.ForeignKey(Area, on_delete=models.SET_NULL, null=True)
    Pin = models.CharField(max_length=6, default=000000)

    def __str__(self):
        return self.user.username


class Doctor(models.Model):
    Doctor_ID = models.AutoField(primary_key=True, auto_created=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Doctor_First_Name = models.CharField(max_length=200)
    Doctor_Last_Name = models.CharField(max_length=200)
    Doctor_DOB = models.DateField(max_length=8, null=True)
    Doctor_Phone_Number = PhoneNumberField(max_length=13)
    Doctor_Email = models.EmailField(default="asd@rew.com")
    Doctor_Gender = models.IntegerField(choices=GENDER_CHOICES, validators=[MinValueValidator(1), MaxValueValidator(4)])
    Doctor_Qualifications = models.CharField(max_length=350, choices=QUALIFICATION_CHOICES)
    Doctor_Specialization = models.CharField(max_length=250, choices=SPECIALIZATION_CHOICES)
    Doctor_Experience = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(80)])
    Doctor_License = models.CharField(default='1234567890', max_length=25, null=True)
    Doctor_Picture = models.ImageField(upload_to='media', default='default-user-image.jpg', null=True)
    Doctor_Corporate = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, default=None, blank=True)
    Doctor_Activate = models.BooleanField(default=False)
    Doctor_Address = models.ForeignKey(ClinicAddress, on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return self.user.username


class DoctorRating (models.Model):
    Doctor_ID = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    Rating = models.DecimalField(max_digits=2, decimal_places=1,
                                 validators=[MinValueValidator(0), MaxValueValidator(5)])


class TimeSlots(models.Model):
    Doctor_ID = models.ForeignKey(Doctor, on_delete=models.CASCADE, name="Doctor_ID")
    Patient_ID = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True , name="Patient_ID")
    day = models.CharField(max_length=10, choices=DAYS)
    date = models.DateField()
    opening_Time = models.TimeField()

    def __str__(self):
        return self.Doctor_ID.user.username


class doctorSchedule(models.Model):
    Doctor_ID = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, name="Doctor_ID")
    day = models.CharField(max_length=10)
    interval = models.IntegerField(choices=slotTimeChoices, default='10')
    openTime = models.TimeField(choices=HOUR_CHOICES)
    closeTime = models.TimeField(choices=HOUR_CHOICES)

    class Meta:
        db_table = 'schedule'

    def __str__(self):
        return self.Doctor_ID.user.username


# class appointmentBooking(models.Model):
#     docUsername = models.CharField(max_length=40)
#     day = models.CharField(max_length=10)
#     slotTime = models.TimeField(auto_now=False )
#     patientUsername = models.CharField(max_length=40)
#
#     def __str__(self):
#         return self.docUsername

templates/Doctor/after_activation.html
<!DOCTYPE HTML>
<html>
{% load staticfiles %}

<head>
    <title>After Activating Mail</title>
    <link href="{% static 'css/style3.css' %}" rel="stylesheet" type="text/css" media="all" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords"
        content="Reset Password Form Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
</head>

<body style="background-color:grey">
    <div class="elelment">
        <div class="element-main" style="width: 50%;font-family: sans-serif;font-size: 20px">
            <p>
                Thank you for your email confirmation........!
            </p>
            <center>
                <span>→ </span> <a href="{% url 'D_index' %}" style="color:#0086E5">Login</a><span
                    style="font-size:17px"> here</span>
            </center>
        </div>
    </div>
</body>

</html>

templates/Doctor/allblogs.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>@{{ name }}&apos;s Blogs</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/helper.css' %}">
</head>

<body>
    {% if blogs %}
    {% for note in blogs %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h2><a
                        href="{% url 'blog-detail' username=note.user.username blog_title=note.title %}">{{ note.title }}</a>
                </h2>
                <small class="text-muted">Date Published: {{ note.date }}</small>
            </div>
            <p class="article-content">{{ note.text | truncatechars:30 }}</p><br>
        </div>
    </article>
    {% endfor %}
    {% endif %}

    {% if err %}
    <p>That doctor does not exist.</p>
    {% endif %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
</body>

</html>

templates/Doctor/checkemail.html
<!DOCTYPE HTML>
<html>
{% load staticfiles %}

<head>
    <title>After Activating Mail</title>
    <link href="{% static 'css/style3.css' %}" rel="stylesheet" type="text/css" media="all" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords"
        content="Reset Password Form Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
</head>

<body style="background-color:grey">
    <div class="elelment">
        <div class="element-main" style="width: 50%;font-family: sans-serif;font-size: 20px">
            <pre>
            Please confirm your email address to complete the registration    </pre>
            <center>
                <span>. </span> <a href="https://mail.google.com/mail/" style="color:#0086E5"><img
                        src="{% static 'images/icons8-google-48.png' %}"> </a>
                <span>. </span><a href="https://login.yahoo.com/" style="color:#0086E5"><img
                        src="{% static 'images/icons8-yahoo-48.png' %}"></a>
                <span>. </span><a href="https://login.live.com/" style="color:#0086E5"><img
                        src="{% static 'images/icons8-microsoft-outlook-48.png' %}"></a></center>
        </div>
    </div>
</body>

</html>

templates/Doctor/doctorSchedule.html
<!DOCTYPE HTML>
<html>

<head>
    <title>Schedule</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>

    {% load crispy_forms_tags %}
    <form class="form-horizontal" method="POST" onsubmit="return myValidation(this)"
        action="{% url 'doctorSchedule' %}">
        {% csrf_token %}
        {{ formset.management_form }}

        <fieldset id="fieldset">
            {% for form in formset %}
            <div id="placeholder">
                <fieldset id="fieldsets">
                    <div id="template">
                        {{ form.day|as_crispy_field}}
                        <div class="form-row">
                            <div class="form-group col-md-4 mb-0">
                                {{ form.m_interval|as_crispy_field}}<br>
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                {{ form.m_openTime|as_crispy_field}}<br>
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                {{ form.m_closeTime|as_crispy_field}}<br>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4 mb-0">
                                {{ form.e_interval|as_crispy_field}}<br>
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                {{ form.e_openTime|as_crispy_field}}<br>
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                {{ form.e_closeTime|as_crispy_field}}<br>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
            {% endfor %}
        </fieldset>


        <div class="row spacer">
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-block btn-primary">Create</button>
            </div>
        </div>
    </form>
    {% load crispy_forms_tags %}


    <script>
        function myValidation(forms) {
            if (forms): {
                alert('form.day');
                return false;
            }
        }
    </script>
</body>

</html>

templates/Doctor/edit_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}

<meta charset="UTF-8">
<title>Profile</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/font-awesome.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/main1.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/util.css" %}">
<link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
<link rel="stylesheet" type="text/css" href="http://jquery-ui.googlecode.com/svn/tags/latest/themes/base/jquery-ui.css"
    media="all" />
{% endblock %}
{% block content %}
<br>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static "img-01.png" %}" alt="IMG">
            </div>
            <form class="login100-form validate-form" method="POST" id="EditProfileForm"
                action="{% url "D_edit_profile" %}" enctype="multipart/form-data">
                {% csrf_token %}
                <span class="login100-form-title">
                    User Profile
                </span>
                {% for field in Profile_form %}
                {{ field.label_tag }}<br>
                <div class="wrap-input100 validate-input input100">
                    {{ field }}
                    <span class="focus-input100"></span>
                </div>
                {% endfor %}
                {% if Profile_form.errors %}
                <p style="font-size: 12px;color: red">{{ Profile_form.errors.Patient_Phone_Number }}
                    Please make sure to add +91 at the start.</p>
                {% endif %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit" value="signup">
                        Submit
                    </button>
                </div>
                <div class="text-center p-t-12">
                    {% if user.is_authenticated %}
                    <a class="txt2" href="{% url 'logout' %}">
                        Log out
                    </a>
                    {% else %}
                    {% endif %}
                    <span class="txt1">
                        here...
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>
{% comment %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_city").change(function () {
        var url = $("#AddressForm").data("areas-url"); // get the url of the `load_cities` view
        var cityId = $(this).val(); // get the selected country ID from the HTML input
        $.ajax({ // initialize an AJAX request
            url: url, // set the url of the request (= localhost:8080/hr/ajax/load-cities/)
            data: {
                'city': cityId // add the country id to the GET parameters
            },
            success: function (data) { // `data` is the return of the `load_cities` view function
                $("#id_area").html(
                    data
                    ); // replace the contents of the city input with the data that came from the server
            }
        });
    });
</script> {% endcomment %}
{% endblock %}

</html>

templates/Doctor/feedback_email.html
{% autoescape off %}
Hi {{ user.username }},
Please Log In before clicking the link.
Please click on the link to give feedback,
http://{{ domain }}{% url 'D_feedback' uidb64=uid token=token %}
{% endautoescape %}

templates/Doctor/index.html
<!DOCTYPE html>
<html>

<head>
    Doctor Index Page
    <a href={% url 'D_edit_profile' %}> Edit Profile </a>
</head>

<body>
    Profile is shown here.
    <br>{{ profile.user }}<br>
    {{ profile.Doctor_First_Name }}<br>
    {{ profile.Doctor_Last_Name }}<br>
    {% if profile.Doctor_Gender == 1 %}
    Male<br>
    {% elif profile.Doctor_Gender == 2 %}
    Female<br>
    {% elif profile.Doctor_Gender == 3 %}
    Transgender<br>
    {% elif profile.Doctor_Gender == 4 %}
    Other<br>
    {% endif %}
    {{ profile.Doctor_DOB }}<br>
    {{ profile.Doctor_Phone_Number }}<br>
    <img src="{{ profile.Doctor_Picture.url }}" height="100" width="100"><br>
    {{ profile.Doctor_Picture.url }}
    {{ profile.Doctor_Qualifications }}<br>
    {{ profile.Doctor_Specialization }}<br>
    {{ profile.Doctor_Experience }}<br>

    <br><br>
    <a href="{% url 'create-blog' %}"><button>Create Blog</button></a>
    <a href={% url 'logout' %}>Logout</a>
</body>

</html>

templates/Doctor/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}

<meta charset="UTF-8">
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/font-awesome.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/main1.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/util.css" %}">
<link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
{% endblock %}
{% block content %}
<br>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static "img-01.png" %}" alt="IMG">
            </div>
            <form class="login100-form validate-form" method="POST" action="{% url 'D_login' %}">
                {% csrf_token %}
                <span class="login100-form-title">
                    Login
                </span>
                {% for field in form %}
                {{ field.label_tag }}<br>
                <div class="wrap-input100 validate-input input100">
                    {{ field }}
                    <span class="focus-input100"></span>
                </div>
                {% if field.help_text %}
                <small></small>
                {% endif %}
                {% endfor %}
                {% if form.errors %}
                <p style="font-size: 12px;color: red">{{ form.get_invalid_login_error }}</p>
                {% endif %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit" value="Login">
                        Login
                    </button>
                </div>
                {% comment %} <div class="text-center p-t-12">
                    <span class="txt1">
                        Forgot
                    </span>
                    <a class="txt2" href="{% url 'password_reset' %}" style="padding-left:7px">
                        Password?
                    </a>
                </div> {% endcomment %}
                <div class="text-center p-t-136">
                    <a class="txt2" href="{% url 'D_signup' %}">
                        Create your Account →
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

</html>

templates/Doctor/not_activated.html
<!DOCTYPE html>
<html>

<head>
    Your profile hasn't been validated and activated yet. Please wait 10 days after registeration and try again.
</head>

<body>
    <a href={% url 'logout' %}>Logout</a>
</body>

</html>

templates/Doctor/profile.html
<!DOCTYPE html>

<html lang="en">
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
<meta charset="UTF-8">
<title>Profile</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/font-awesome.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/main1.css" %}">
<link rel="stylesheet" type="text/css" href="{% static  "css/util.css" %}">
<link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
<link rel="stylesheet" type="text/css" href="http://jquery-ui.googlecode.com/svn/tags/latest/themes/base/jquery-ui.css"
    media="all" />
{% endblock %}
{% block content %}}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static "img-01.png" %}" alt="IMG">
            </div>

            <form class="login100-form validate-form" method="POST" id="AddressForm"
                data-areas-url="{% url 'P_ajax_load_areas' %}" action="{% url "D_profile" %}">
                {% csrf_token %}
                <span class="login100-form-title">
                    User Profile
                </span>
                {% for field in Profile_form %}
                {{ field.label_tag }}<br>
                <div class="wrap-input100 validate-input input100">
                    {{ field }}
                    <span class="focus-input100"></span>
                </div>
                {% endfor %}
                {% for field in address_form %}
                {{ field.label_tag }}<br>
                <div class="wrap-input100 validate-input input100">
                    {{ field }}
                    <span class="focus-input100"></span>
                </div>
                {% endfor %}
                {% if Profile_form.errors %}
                <p style="font-size: 12px;color: red">{{ Profile_form.errors.Patient_Phone_Number }}
                    Please make sure to add +91 at the start</p>
                {% endif %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit" value="signup">
                        Submit
                    </button>
                </div>
                <div class="text-center p-t-12">
                    {% if user.is_authenticated %}
                    <a class="txt2" href="{% url 'logout' %}">
                        Log out
                    </a>
                    {% else %}
                    {% endif %}
                    <span class="txt1">
                        here...
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_city").change(function () {
        var url = $("#AddressForm").data("areas-url"); // get the url of the `load_cities` view
        var cityId = $(this).val(); // get the selected country ID from the HTML input
        $.ajax({ // initialize an AJAX request
            url: url, // set the url of the request (= localhost:8080/hr/ajax/load-cities/)
            data: {
                'city': cityId // add the country id to the GET parameters
            },
            success: function (data) { // `data` is the return of the `load_cities` view function
                $("#id_area").html(
                    data
                    ); // replace the contents of the city input with the data that came from the server
            }
        });
    });
</script>

</html>